### ISSUE TITLE
Hook Needed for Unchanged Cert

### ISSUE THREAD

**Issue by the-solipsist** [RoliSoft/LetsEncrypt-CloudFlare-Hook#1]
While this doesn't affect the functionality, for sake of completeness, it would be good to include code for the "unchanged_cert" response, since currently one gets:

`/etc/letsencrypt.sh/hook.sh: line 192: unchanged_cert: command not found`

**Comment by RoliSoft** [comment]
Fixed by 11c5790f6a760c1917a1a9a5bda5f90cdbb3297e.
