### ISSUE TITLE
Parameter mismatch in deploy.sh.example

### ISSUE THREAD

**Issue by the-solipsist** [RoliSoft/LetsEncrypt-CloudFlare-Hook#3]
deploy.sh.example checks for 4 parameters being passed to it.  However, hook.sh, thanks to https://github.com/RoliSoft/LetsEncrypt-CloudFlare-Hook/commit/11c5790f6a760c1917a1a9a5bda5f90cdbb3297e , now passes 5 parameters, not 4.

Also, in letsencrypt.sh, there's an additional parameter, TIMESTAMP, that may be passed, taking the total to 6.

**Comment by RoliSoft** [comment]
Fixed by 97da8e69357313943dc96aaa73a87c8fe5adeed0.
